include:
  - project: plos/gcp-global
    file: /gitlab-ci-k8s+tf.yml
  - template: Security/SAST.gitlab-ci.yml


stages:
  - test
  - integration

variables:
  PYTHON_VERSION: "3.10.15"
  WORKDIR: "/tmp/editorial_manager_transfer_service"
  JANEWAY_PATH: "$WORKDIR/janeway"
  PLUGIN_PATH: "$JANEWAY_PATH/src/plugins/editorial_manager_transfer_service"
  DJANGO_SETTINGS_MODULE: "core.settings"
  JANEWAY_SETTINGS_MODULE: "core.settings"
  PYTHONPATH: "$JANEWAY_PATH/src"
  # Google Backend Credentials is required for the integration test image
  GOOGLE_BACKEND_CREDENTIALS: ${GCR_AUTH_JSON_FILE}

cache:
  key: "${CI_COMMIT_REF_SLUG}-pip"
  paths:
    - ~/.cache/pip/

# --------------------------------------------
# Django unit tests
# --------------------------------------------
django_tests:
  stage: test
  image: python:${PYTHON_VERSION}
  before_script:
    - export GOOGLE_APPLICATION_CREDENTIALS=${GCR_AUTH_JSON_FILE}
    - apt-get update -qq && apt-get install -y git
    - mkdir -p $WORKDIR
    - cd $WORKDIR
    # Clone Janeway
    - git clone --branch develop https://github.com/PLOS/janeway.git $JANEWAY_PATH
    # Copy this plugin into Janeway plugins folder
    - mkdir -p $PLUGIN_PATH
    - cp -r $CI_PROJECT_DIR/* $PLUGIN_PATH/
    # Install dependencies
    - python -m pip install --upgrade pip
    - find $WORKDIR -name "*requirements.txt" -type f -exec pip install -r '{}' ';'
    # Import Janeway dev settings
    - cp $JANEWAY_PATH/src/core/dev_settings.py $JANEWAY_PATH/src/core/settings.py
  script:
    - cd $JANEWAY_PATH
    - python src/manage.py test editorial_manager_transfer_service
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "main"'
  #   - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  artifacts:
    when: always
    paths:
      - $JANEWAY_PATH/test_results.xml
    reports:
      junit: $JANEWAY_PATH/test_results.xml

# --------------------------------------------
# Integration tests
# --------------------------------------------
integration_tests:
  stage: integration
  image: gcr.io/plos-mgmt/plos-test:python-3-11
  needs:
    - job: django_tests
  script:
    - cd tests/integration
    - mkdir -p ./pytest_report
    - pipenv install
    - pipenv run pytest -v -l --reruns 3 --reruns-delay 3 --timeout=600 \
        --html='./pytest_report/pytest_report.html' api/
  artifacts:
    when: always
    paths:
      - tests/integration/pytest_report/
  # rules:
    # - if: '$CI_COMMIT_BRANCH == "main"'
    # - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
