# Generated by Django 4.2.22 on 2025-09-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0068_issue_cached_display_title_a11y_and_more'),
        ('submission', '0088_auto_20250506_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('EX', 'Export Message'), ('IM', 'Import Message')], default='EX', max_length=2)),
                ('message', models.TextField()),
                ('message_date_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
    ]
