# Generated by Django 4.2.22 on 2025-10-10 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submission', '0088_auto_20250506_1214'),
        ('journal', '0068_issue_cached_display_title_a11y_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_state', models.CharField(choices=[('000', 'No Error Detected'), ('001', 'Article is in Flight'), ('002', 'Failed Bundling'), ('003', 'Editorial Manager Rejected at SFTP')], default='001', max_length=3)),
                ('message_date_time_start', models.DateTimeField(auto_now_add=True)),
                ('message_date_time_stop', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
            ],
        ),
        migrations.CreateModel(
            name='TransferLogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('EX', 'Export Message'), ('IM', 'Import Message')], default='EX', max_length=2)),
                ('message', models.TextField()),
                ('message_date_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.article')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.journal')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editorial_manager_transfer_service.transferreport')),
            ],
        ),
    ]
