# Generated by Django 4.2.22 on 2026-01-03 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0091_alter_field_slug'),
        ('editorial_manager_transfer_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialManagerSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('editorial_manager_section_id', models.CharField(max_length=64)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.section')),
            ],
        ),
    ]
