name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.15]

    steps:
    - name: Fetch Main Janeway Branch
      uses: actions/checkout@v4
      with:
        repository: PLOS/janeway
        ref: develop
    - name: Fetch Editorial Manager Transfer Service
      uses: actions/checkout@v4
      with:
        path: ./src/plugins
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        sudo find . -name "*requirements.txt" -type f -exec pip3 install -r '{}' ';'
    - name: Run Tests
      run: |
        python manage.py test
